### PR TITLE
avoid overlapping

### LINKED ISSUE #41: Problem with 16:9 screens
I have a little problem seeing the beta web page with the footer.

screenshot from 2017-05-27 18 33 13

### PR DESCRIPTION
**Pull request by AsLogd**
I guess this would make a quick fix. Switch to relative if there's not enough space. But maybe you would like to keep the social links in spite the lack of space. In this case we have just have to separate in two queries
fixes #41

### CODE REVIEW

**Comment by wailingtam** [comment]
This is really a quick fix, I'm not quite into it. 😥 `max-height: 685p` would make the social links not appear in most of the mobile devices.
Earlier today I tried to fix this too but I just couldn't figured it out and make it work. 😣

**Comment by AsLogd** [comment]
We could just make the links appear. With the "relative" position there would be scroll. I set it to that height because it's the minimum space needed to fit. It's scrolling or removing the links. If you prefer scrolling I can change it np

**Comment by wailingtam** [comment]
Yeah, I know why you set that height and I also thought about making it scrollable but I think that the initial idea was to have one page with no scroll so... we're stucked.

I'm gonna send you what I've got and maybe you can figure it out

**Comment by casassg** [comment]
Let me try to do this: https://css-tricks.com/snippets/css/sticky-footer/

**Comment by casassg** [comment]
Fixed already in #46

**Pull request closed without merging**
