### PR TITLE
Style and lint fixes

### PR DESCRIPTION
**Pull request by wailingtam**
1st commit:
- I've added a few pixels (4px to be precise) to the email input height. I think it is necessary and that it was the reason why it gave us the impression that the input was a bit small. Tell me what you think.
- I've reduced some margins because we've added a new line for the lenny faces and the whole layout has to adapt for it (No one realized about this "error")
- I forgot to add the tab indentation rule to the js linter 😅 

2nd commit:
- I've removed all unused variables and classes from the stylesheet. Plus, I've reordered the classes by the order how they appear in the html. The mess was bothering me 😣

**Tip**: Check the two commits separately.

### CODE REVIEW

**Comment by wailingtam** [comment]
Nono. I'm settings tabs as the indentation to use.

**Comment by wailingtam** [comment]
@casassg don't merge this right after #39. Cause I've to edit `index.html`  in `/src`, which I can't until #39 is merged ☺️

**Comment by casassg** [comment]
I know dont worry 👌

**Comment by wailingtam** [comment]
@casassg it's good to go now. I don't know what's the problem with codeclimate. Is the word `HACK`an issue? 😂

**Comment by casassg** [comment]
Idk, codeclimate being codeclimate. marked as invalid. now we are good

**Pull request merged**
