### PR TITLE
Add sticky footer

### PR DESCRIPTION
**Pull request by casassg**
After seeing all the problems we are having with the current website, I decided to refactor a bit and remove some stuff:

- Removed lenny faces. I couldn't find a way to keep and looking good for sponsors. Long live the lenny faces
- Set footer to sticky instead of absolute. See thus beautiful hack: https://css-tricks.com/snippets/css/sticky-footer/
- Added some padding between elements so that the webpage breaths a bit more.

### CODE REVIEW

**Comment by casassg** [comment]
Hey I know, I shouldn't do this without getting a review... But we need to release and the current website has some messed up stuff. I think I'll merge. I'll leave it open if by any chance any of you are awake and want to review really early. Will merge at 7AM CEST time and change nginx to point at this instead. If something is wrong, auto deployment is activated so you can change stuff here and push to master to fix it.

**Comment by casassg** [comment]
DAAAMN it scrolling bar. Let me take a look. How did you test it? Device..?

**Comment by casassg** [comment]
Also, lenny faces are being removed so we look more serious to sponsors. I've been recommended to do so.

**Comment by ofpau** [comment]
Firefox and Chromium on a 13" laptop, 1920×1080 px. 
Chromium displaying as an iPhone 5, same happens.

iphone

**Comment by ofpau** [comment]
I don't see how the lenny faces could hurt us, we're _serious_ about what we do but we're organizing a **fun** event.

I understand that the recommendation probably comes from someone with more experience so I'm okay with this for now. But let's discuss it with the team.

**Comment by ofpau** [comment]
This removes the scrolling bar on my screens but keeps the footer on mobile. Sadly I don't fully understand why or how.

**Comment by casassg** [comment]
1- Agree with further discussing it with the rest of the team. But I prefer to be safe for the time being. We can add the lenny faces back if all departments agree with it.

2-  Fixed the scroll with max-width. It was the social media links taking too much space when doing a new line

**Comment by dasilvacontin** [comment]
Try to make granular commits so that stuff can be rolled back if necessary.

> Also, lenny faces are being removed so we look more serious to sponsors. I've been recommended to do so.

Can you elaborate?

**Comment by casassg** [comment]
@dasilvacontin it was feedback provided by mllobet. it didnt seem too serious for sponsors. I'm not sure about it, I removed it just in case (better be safe than sorry in this case). Also, the entire point of the current website is more for sponsors to see that we are organizing a new edition than for hackers. We can add them on the final website maybe?

**Comment by dasilvacontin** [comment]
Good point about landing being mainly for sponsors. Where is that feedback you are talking about, though? Link?

**Comment by casassg** [comment]
Private message -.-

**Pull request merged**
