### PR TITLE
avoid fb cache

### PR DESCRIPTION
**Pull request by casassg**
Fb is caching out OG_IMAGE, we dont want that... how to fix it? Add a get parameter 🙃

### CODE REVIEW

**Comment by dasilvacontin** [comment]
Forcing facebook's cache refresh didn't work? https://developers.facebook.com/tools/debug/sharing/?q=hackupc.com

**Comment by ofpau** [comment]
And then what about Twitter, Slack, Whatsapp,...? The way it's been done works for all those caches.

**Comment by dasilvacontin** [comment]
@ofpau good point, ty.

**Comment by ofpau** [comment]
Was about to say that this issue's name should be more general, thx for changing it.

**Comment by dasilvacontin** [comment]
@ofpau btw, it could still fail for those apps that cache the whole HTML, image, etc for some time.

**Comment by ofpau** [comment]
Oh, could be. In case that's actually happening we can look into that. I don't know any particular examples though.

**Comment by casassg** [comment]
No it didn't work. Our image cache is enabled for 5 days in nginx. I
guessed that was the problem

**Pull request merged**
