### PR TITLE
Make email required

### PR DESCRIPTION
**Pull request by casassg**
In order to avoid people ending on MailChimp sign up page, make email required in the form. Avoids confusions

### CODE REVIEW

**Comment by wailingtam** [comment]
Have you tested it? It doesn't work for me 😕

**Comment by casassg** [comment]
Removed novalidate tag and tested on local. Let me know if this works for you now

**Comment by wailingtam** [comment]
@casassg werks

**Comment by casassg** [comment]
@wailingtam can you approve changes then?

**Pull request merged**
